var express = require('express');
var router = express.Router();

var generos = ['Classic Rock', 
				'Psychedelic Rock', 
				'Grunge', 
				'Soul', 
				'Folk', 
				'Clasica', 
				'Alternativo', 
				'Electropop', 
				'BritPop', 
				'Electronica'];

var disco = [{ 	titulo: 'Unplugged in NY',
				autor: 'Nirvana',
            	genero: '3',
			   	img:'images/harry_potter.png',
			   	año: '1995',
			   	codigo: '001'
			 },
			 { 	titulo: 'The Doors',
				autor: 'The Doors',
            	genero: '1',
			   	img:'images/doors1.png',
			   	año: '1967',
			   	codigo: '002'
			 },
			 { 	titulo: 'Strange Days',
				autor: 'The Doors',
            	genero: '1',
			   	img:'images/doors1.png',
			   	año: '1967',
			   	codigo: '003'
			 },
			 { 	titulo: ' The Soft Parade',
				autor: 'The Doors',
            	genero: '1',
			   	img:'images/doors1.png',
			   	año: '1969',
			   	codigo: '004'
			 },
			 { 	titulo: 'Morrison Hotel',
				autor: 'The Doors',
            	genero: '1',
			   	img:'images/doors1.png',
			   	año: '1970',
			   	codigo: '005'
			 },
			 { 	titulo: 'Waiting For The Sun',
				autor: 'The Doors',
            	genero: '1',
			   	img:'images/doors1.png',
			   	año: '1968',
			   	codigo: '006'
			 },
			 { 	titulo: 'LA Woman',
				autor: 'The Doors',
            	genero: '1',
			   	img:'images/doors1.png',
			   	año: '1971',
			   	codigo: '007'
			 },
			 { 	titulo: 'Speak and Spell',
				autor: 'Depeche Mode',
            	genero: '7',
			   	img:'images/depeche1.png',
			   	año: '1981',
			   	codigo: '008'
			 },
			 { 	titulo: 'A Broken Frame',
				autor: 'Depeche Mode',
            	genero: '7',
			   	img:'images/depeche1.png',
			   	año: '1982',
			   	codigo: '009'
			 },
			 { 	titulo: 'Construction Time Again',
				autor: 'Depeche Mode',
            	genero: '7',
			   	img:'images/depeche1.png',
			   	año: '1983',
			   	codigo: '010'
			 },
			 { 	titulo: 'Some great Reward',
				autor: 'Depeche Mode',
            	genero: '7',
			   	img:'images/depeche1.png',
			   	año: '1984',
			   	codigo: '011'
			 },
			 { 	titulo: 'Black Celebration',
				autor: 'Depeche Mode',
            	genero: '7',
			   	img:'images/depeche1.png',
			   	año: '1986',
			   	codigo: '012'
			 },
			 { 	titulo: 'Music for the Masses',
				autor: 'Depeche Mode',
            	genero: '7',
			   	img:'images/depeche1.png',
			   	año: '1987',
			   	codigo: '013'
			 },
			 { 	titulo: 'I Created Disco',
				autor: 'Calvin Harris',
            	genero: '9',
			   	img:'images/calvinharris.png',
			   	año: '2007',
			   	codigo: '014'
			 },
			 { 	titulo: 'Ready for the Weekend',
				autor: 'Calvin Harris',
            	genero: '9',
			   	img:'images/calvinharris.png',
			   	año: '2009',
			   	codigo: '015'
			 },
			 { 	titulo: '18 Months',
				autor: 'Calvin Harris',
            	genero: '9',
			   	img:'images/calvinharris.png',
			   	año: '2012',
			   	codigo: '016'
			 },
			 { 	titulo: 'Motion',
				autor: 'Calvin Harris',
            	genero: '9',
			   	img:'images/calvinharris.png',
			   	año: '2014',
			   	codigo: '017'
			 },
			 { 	titulo: 'Funk Wav Bounces Vol.1',
				autor: 'Calvin Harris',
            	genero: '9',
			   	img:'images/calvinharris.png',
			   	año: '2017',
			   	codigo: '018'
			 },
			 { 	titulo: 'Please Please Me',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1963',
			   	codigo: '019'
			 },
			 { 	titulo: 'With The Beatles',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1963',
			   	codigo: '020'
			 },
			 { 	titulo: "A Hard Day's Night",
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1964',
			   	codigo: '021'
			 },
			 { 	titulo: 'Beatles for Sale',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1964',
			   	codigo: '022'
			 },
			 { 	titulo: 'Help',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1965',
			   	codigo: '023'
			 },
			 { 	titulo: 'Rubber Soul',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1965',
			   	codigo: '024'
			 },
			 { 	titulo: 'Revolver',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1966',
			   	codigo: '025'
			 },
			 { 	titulo: "Sgt. Peper's Lonely Hearts Club Band",
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1967',
			   	codigo: '026'
			 },
			 { 	titulo: 'Magical Mystery Tour',
				autor: 'The Beatles',
            	genero: '8',
			   	img:'images/beatles.png',
			   	año: '1967',
			   	codigo: '027'
			 }];